### ISSUE TITLE
Google Docs

### ISSUE THREAD

**Issue by DevinSmith69** [wavenet-for-chrome/extension#25] opened 2020-05-27 07:21 UTC
I can't seem to play or download scripts through google docs in chrome, set the shortcuts to be global in chrome as well but no luck, any ideas?

**Comment by pgmichael** [comment] 2021-02-02 22:34
Thanks for opening an issue. I'm closing this since it's a duplicate of https://github.com/wavenet-for-chrome/extension/issues/16.

**Closed by pgmichael** 2021-02-02 22:34 UTC
